
import { prismaClient } from "./index";

// this type as auto-generated by prisma
import { OTP } from "@prisma/client";

async function main(): Promise<OTP[]> {
    const newOTP = await prismaClient.oTP.createMany({
        data: {
            email: "nddminh2021@gmail.com",
            code: "123456",
            expiresAt: new Date(Date.now() + 1000 * 5), // 5 seconds
        },
    });

    if (!newOTP) {
        console.error("Failed to create new OTP");
        return [];
    }

    const otp = await prismaClient.oTP.findMany({
        where: {
            email: "nddminh2021@gmail.com",
        },
    });
    return otp;
}

main().then((OTPList) => {
    OTPList.forEach((OTP) => {
        console.log(`Found an OTP of email ${OTP.email}: ${OTP.code}, which was created at: ${OTP.createdAt}`);
    });
});